/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pdf_filler

import com.gitlab.pdftk_java.com.lowagie.text.pdf.*
import com.gitlab.pdftk_java.pdftk
import java.nio.file.Files
import java.nio.file.Paths

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    val t = pdftk()
    val reader = PdfReader("file.pdf")
    val form = XfdfReader("file.xfdf")
    val outputStream = Files.newOutputStream(Paths.get("/tmp/test.pdf"))

    // Code from com.gitlab.pdftk_java.filter
    val writer_p = PdfStamperImp(reader, outputStream, '\u0000', false /* append mode */)
    val fields_p = writer_p.getAcroFields()
    writer_p.setFormFlattening(true)
    fields_p.setGenerateAppearances(true)
    fields_p.setFields(form)
    writer_p.close()
}
