/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pdf_filler

import com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader
import com.gitlab.pdftk_java.com.lowagie.text.pdf.XfdfReader
import java.nio.file.Files
import java.nio.file.Paths

fun main() {
    val reader = PdfReader("file.pdf")
    val form = XfdfReader("file.xfdf")
    val outputStream = Files.newOutputStream(Paths.get("/tmp/test.pdf"))
    PdfFiller(reader).fill(form, outputStream)
}
