/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package eu.eutampieri.pdf_filler

import io.ktor.server.application.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import eu.eutampieri.pdf_filler.plugins.*
import com.gitlab.pdftk_java.com.lowagie.text.pdf.PdfReader
import com.gitlab.pdftk_java.com.lowagie.text.pdf.XfdfReader
import java.nio.file.Files
import java.nio.file.Paths

/*fun main() {
    val reader = PdfReader("file.pdf")
    val form = XfdfReader("file.xfdf")
    val outputStream = Files.newOutputStream(Paths.get("/tmp/test.pdf"))
    PdfFiller(reader).fill(form, outputStream)
}*/
fun main(args: Array<String>): Unit = io.ktor.server.netty.EngineMain.main(args)

fun Application.module() {
    configureRouting()
}